/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    fontFamily: {
      yanone: ['"Yanone Kaffeesatz"', "sans-serif"],
      nunito: ['"Nunito"', "sans-serif"],
      "open-sans": ['"Open Sans"', "sans-serif"],
      poppins: ['"Poppins"', "sans-serif"],
    },
    colors: {
      "azul-100": "#4EA6B8;",
      "azul-header": "#2E8496",
      "azul-borda-fundo-1": "#96D1D5;",
      "azul-fundo-1": "#F2FEFF;",
      "azul-fundo-2": "#E8FDFF;",
      "azul-tipografia-texto": "#222E2F;",
      "azul-tipografia-titulo": "#050E21;",
      "cinza-tipografia-texto": "#060316;",
      "verde-botao": "#8CF122;",
      "verde-hover-botao": "#6AC707;",
      "verde-active-botao": "#5EB403;",
      "verde-focus-botao": "#B3FC66;",
      "verde-Pbotao": "#2EFF2E;",
      "verde-Phover": "#29E041;",
      "borda-roxa": "#0B0013;",
      "borda-azul-25": "#0C182E;",
      "amarelo-fundo": "#FFE280;",
      "amarelo-Pbotao": "#BFFF0F;",
      "amarelo-Phover": "#A5D81B;",
      "roxo-tipografia-titulo": "#0B0521;",
      "roxo-tipografia-texto": "#14111B;",
    },
    backgroundImage: {
      vetor1: "url('/src/assets/vetor-home-1.svg')",
      vetor2: "url('/src/assets/vetor-home-2.svg')",
      vetor3: "url('/src/assets/vetor-home-3.svg')",
      banner: "url('/src/assets/banner-home.png')",
      banner: "url('/src/assets/banner-home.png')",
      "banner-mobile": "url('/src/assets/banner-home-mobile.png')",
    },
  },
  plugins: [],
};
